# Generated by Django 4.1.7 on 2023-02-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topis',
            new_name='Topic',
        ),
    ]
