# Generated by Django 4.1.7 on 2023-03-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dete_added',
            new_name='date_added',
        ),
    ]
